CREATE TABLE Users (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Email TEXT,
	DisplayName TEXT,
	PasswordHash TEXT,
	Salt TEXT,
	SsoUser INTEGER
);

CREATE TABLE Notifications (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER,
    Subject TEXT,
    Message TEXT,
    isLink INTEGER,
    Link TEXT,
    Seen INTEGER
);

CREATE TABLE Projects (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	UserId INTEGER,
	Title TEXT,
	Colour TEXT
);

CREATE TABLE ProjectMembership (
	UserId INTEGER,
	ProjectId INTEGER
);

CREATE TABLE ProjectTask (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	ProjectId INTEGER,
	UserId INTEGER,
	Name TEXT,
	Description TEXT
);