CREATE TABLE Users (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Email TEXT,
	DisplayName TEXT,
	PasswordHash TEXT,
	Salt TEXT,
	SsoUser INTEGER
);

CREATE TABLE Notifications (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER,
    Subject TEXT,
    Message TEXT,
    isLink INTEGER,
    Link TEXT,
    Seen INTEGER
);

CREATE TABLE Projects (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	UserId INTEGER,
	Title TEXT,
	Colour TEXT
);

CREATE TABLE ProjectMemberships (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	UserId INTEGER,
	ProjectId INTEGER,
	IsFavourite INTEGER
);

CREATE TABLE ProjectTasks (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	ProjectId INTEGER,
	UserId INTEGER,
	Label TEXT,
	Description TEXT,
	Completed INT
);